### ISSUE TITLE
Time-consuming Object Recognition

### ISSUE THREAD

**Issue by precyl** [anobongjimwel/pulut-pukyutan-unit-srv-php#1]
The Google Cloud Vision API to be used in our project seems to take time to recognize objects specially when the internet is slow. Worst is that when internet is out of reach, it is not able to recognize the objects.

**Comment by anobongjimwel** [comment]
Will be using OpenCV in the future to fix the issue

**Comment by anobongjimwel** [comment]
Please find this issue in the @anobongjimwel/honeypi repository
